filme/urls.py
from django.urls import path, reverse_lazy
from .views import HomeFilmes, Homepage, Detalhesfilme, PesquisaFilme, Paginaperfil, Criarconta
from django.contrib.auth import views as auth_view


app_name = 'filme'

urlpatterns = [
    path('', Homepage.as_view(), name='homepage'),
    path('filmes/', HomeFilmes.as_view(), name='homefilmes'),
    path('filmes/<int:pk>/', Detalhesfilme.as_view(), name='detalhesfilme'),
    path('pesquisa/', PesquisaFilme.as_view(), name='pesquisafilme'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('editarperfil/<int:pk>', Paginaperfil.as_view(), name='editarperfil'),
    path('criarconta/', Criarconta.as_view(), name='criarconta'),
    path('mudarsenha/', auth_view.PasswordChangeView.as_view(template_name='editarperfil.html', success_url=reverse_lazy('filme:homefilmes')), name='mudarsenha'),



]

lzkfilmes/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls' ,namespace='filme')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filme/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

# Create your models here.
LISTA_CATEGORIAS = (
    ('ANALISES','Análises'),
    ('PROGRAMACAO','Programação'),
    ('APRESENTACAO','Apresentação'),
    ('OUTROS','Outros'),

)
#criar filmes
class Filme(models.Model):
    titulo = models.CharField(max_length=100)
    thumb = models.ImageField(upload_to='thumb_filmes')
    descricao =models.TextField(max_length=1000)
    categoria = models.CharField(max_length=15, choices=LISTA_CATEGORIAS)
    visualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.titulo

#criar ep
class Episodio(models.Model):
    filme = models.ForeignKey('Filme', related_name='episodios', on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    video = models.URLField()

    def __str__(self):
        return self.titulo


class Usuario(AbstractUser):
    filmes_vistos = models.ManyToManyField("Filme")

filme/forms.py
from django.contrib.auth.forms import  UserCreationForm
from .models import Usuario
from django import forms


class FormHomepage(forms.Form):
    email = forms.EmailField(label=False)


class CriarContaForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')

filme/views.py
from django.shortcuts import render, redirect, reverse
from .models import Filme, Usuario
from .forms import CriarContaForm, FormHomepage
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin


def homepage(request):
    return render(request, "homepage.html")

class Homepage(FormView):
    template_name = "homepage.html"
    form_class = FormHomepage

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:

            return redirect('filme:homefilmes')
        else:
            return super().get(request, *args, **kwargs)

    def get_success_url(self):
            email = self.request.POST.get('email')
            usuarios = Usuario.objects.filter(email=email)
            if usuarios:
                return reverse('filme:login')
            else:
                return reverse('filme:criarconta')


class HomeFilmes(LoginRequiredMixin, ListView):
    template_name = 'homefilmes.html'
    model = Filme

class Detalhesfilme(LoginRequiredMixin, DetailView):
    template_name = 'detalhesfilme.html'
    model = Filme

    def get(self, request, *args, **kwargs):
        filme = self.get_object()
        filme.visualizacoes += 1
        filme.save()
        usuario = request.user
        usuario.filmes_vistos.add(filme)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(Detalhesfilme, self).get_context_data(**kwargs)
        filmes_relacionados = Filme.objects.filter(categoria=self.get_object().categoria)
        context['filmes_relacionados'] = filmes_relacionados
        return context

class PesquisaFilme(LoginRequiredMixin, ListView):
    template_name = 'pesquisa.html'
    model = Filme

    def get_queryset(self):
        termo_pesquisa = self.request.GET.get('query')
        if termo_pesquisa:
            object_list = Filme.objects.filter(titulo__icontains=termo_pesquisa)
            return object_list
        else:
            return  None



class Paginaperfil(LoginRequiredMixin, UpdateView):
    template_name = "editarperfil.html"
    model = Usuario
    fields = ['first_name', 'last_name', 'email']

    def get_success_url(self):
        return reverse('filme:homefilmes')

class Criarconta(FormView):
    template_name = "criarconta.html"
    form_class = CriarContaForm

    def get_success_url(self):

        def form_valid(self, form):
            form.save()
            return super().form_valid(form)

        return reverse('filme:login')

filme/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block titulo %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://cdn.tailwindcss.com"></script>

    {% block head %}
    {% endblock %}

</head>
<body class="bg-black text-gray-100 font-primary">

    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}

    <script>
        const nav = document.querySelector('nav')

        document.addEventListener("scroll",e=>{
            if(scrollY>100){
                if(scrollY>window.innerHeight){
                nav.classList.add('invisible')
            }else{
                nav.classList.add('bg-gray-900')
                nav.classList.remove('invisible')
            }
            }else{
                nav.classList.remove('bg-gray-900')
                nav.classList.remove('invisible')
            }
        })
    </script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esn.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esn.js"></script>



</body>
</html>

filme/templates/criarconta.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}

{% endblock %}

{% block content %}



    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/bgnetflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Crie uma conta para continuar</legend>
                    {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 px-3 text-white w-full md:text-lg rounded-md" type="submit">Criar Conta</button>
            </form>

        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2021</li>
            <li> Feito com Python (Django) LZKSTRAIN </li>
            <li>lzkflix/li>
        </ul>
    </footer>

        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Crie uma conta para continuar</legend>
                </fieldset>
                <button class="bg-primary_red py-1 px-3 text-white w-full md:text-lg rounded-md" type="submit">Criar Conta</button>
            </form>

        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2021</li>
            <li> Feito com Python (Django) LZKSTRAIN </li>
            <li>lzkflix/li>
        </ul>
    </footer>



{% endblock %}

filme/templates/detalhesfilme.html
{% extends 'base.html' %}

{% block titulo %}

Homefilmes lzkflix


{% endblock %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
        <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{ object.thumb.url }}');">
            <div>
                <h2 class="text-6xl font-semibold text-white my-4">
                    {{ object.titulo }}
                </h2>
                <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                    {{ object.descricao|slice:':50' }}...
                </p>
                <div class="flex my-4">
                    <a href= "{{ object.episodios.first.video }}">
                        <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                            <ion-icon name="play" class="text-2xl"></ion-icon>
                            <span class="ml-3 font-medium">
                                Play
                            </span>
                        </button>
                    </a>
                </div>
            </div>
        </section>
        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-3xl font-medium">
                  Descrição
                </h2>
                <div class="flex justify-left  items-center min-w-full  movie_lis">
                    <p class="text-gray-100 text-lg">
                          {{ object.descricao }}
                    <br>
                    Visualizações: {{ object.visualizacoes }}
                    </p>
                </div>

                <div style='margin-top:2rem;margin-bottom:2rem;'>
                    <h2 class="text-gray-200 text-3xl font-medium">
                        Episódios

                    </h2>
                    {% for episodio in object.episodios.all %}
                        <h3 class='text-lg'>
                            <a href="{{ episodio.video }}">
                                <p>Episodios {{ forloop.counter }} : {{ episodio.titulo }}</p>
                            </a>
                        </h3>
                       {% endfor %}

                </div>

            </div>
        </section>

        <section class='bg-primary_black flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Relacionados
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                    {% for filme in filmes_relacionados %}
                    <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                        <a href="{% url 'filme:detalhesfilme' filme.id %}">
                                <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt="">
                        </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>

    </main>




<div class="py-12">
    <hr>
    <h1>Esse é o detalhe do Filme: {{ object.titulo }}</h1>
    <p>{{ object }}</p>
   <p>{{ object.descricao }}</p>
    <p>Visualizações: {{ object.visualizacoes }}</p>
    <img src="{{ object.thumb.url }}">

    <h2>Episodios</h2>
    {% for episodio in object.episodios.all %}
    <a href="{{ episodio.video }}">

        Episodios {{ forloop.counter }} : {{ episodio.titulo }}
    </a>
    {% endfor %}

</div>
<div class="py-10">
    <b><h2>Filmes Relacionados</h2></b>
    {% for filme in filmes_relacionados %}
    <p>
        <a href ="{% url 'filme:detalhesfilme' filme.pk %}">
            {{ filme.titulo }}
        </a>
    </p>
    {% endfor %}

</div>
{% endblock %}

filme/templates/editarperfil.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
editar perfil
{% endblock %}

{% block content %}


    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/bgnetflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h2 class="text 2xl">{{ user.username }}</h2>

            <form method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Edite os campos abaixo para editar seu perfil</legend>
                {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md" type="submit">Editar Perfil</button>
            </form>
            <small><a href="{% url 'filme:mudarsenha' %}">Quer mudar sua senha?</a></small>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2021</li>
            <li> Feito com Python (Django)</li>
            <li>Hashtag</li>
        </ul>
    </footer>





{% endblock %}

filme/templates/homefilmes.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Homefilmes lzkflix
{% endblock %}

{% block head %}
<style>
html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background-color: #000;
  font-family: Arial;
}

h1 {
  color: red;
  text-align: center;
}

.wrapper {
  display: grid;
  grid-template-columns: repeat(3,100%);
  overflow:hidden;
  scroll-behavior: smooth;

  section {
    width: 100%;
    position: relative;
    display: grid;
    grid-template-columns: repeat(5, auto);
    margin: 20px 0;

    .item {
      position: relative;
      padding: 0 2px;
      transition: $duration all;

      &:hover {
        margin: 0 40px;
        transform: scale(1.2);
      }


      .heading {
        position: absolute;
        bottom: 20px;
        left: 20px;
        color: #fff;
      }

      .duration {
        position: absolute;
        bottom: 0;
        left: 20px;
        color: #fff;
      }

    }

    .arrow__btn {
      position: center;
      color: #fff;
      text-decoration: none;
      font-size: 6em;
      background:rgb(0,0,0);
      width: 80px;
      padding: 20px;
      text-align: center;
      z-index: 1;
    }

    .left-arrow {
      top:0; bottom:0; left:0;
      background: linear-gradient(-90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
    }

    .right-arrow {
      top:0; bottom:0; right: 0;
      background: linear-gradient(90deg, rgba(0,0,0,0) 0%, rgba(0,0,0,1) 100%);
    }

  }
}
</style>
{% endblock %}

{% block content %}
<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex items-end bg-cover" style="background-image: url('{{ filme_destaque.thumb.url }}');">
        <div>
            <h2 class="text-6xl font-semibold text-white my-4">
            {{ filme.destaque.titulo }}
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                {{ filme.destaque.descricao }}
            </p>
            <div class="flex my-4">
                <a href="{% url 'filme:detalhesfilme' filme_destaque.id %}">
                    <button class="flex items-center bg-white py-2 px-5 rounded-md" style='color:black;'>
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium " >
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative">
            <div class="wrapper grid overflow-visible scroll-smooth">
                <h2 class="text-gray-200 text-2xl font-medium">
                    Novo
                </h2>
                <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2" class="arrow__btn text-6xl page">‹</a>
                    {% for filme in lista_filmes_recentes %}
                    {% if forloop.counter < 5 %}
                    <div class="item h-64 w-1/4 m-4">
                        <a href="{% url 'filme:detalhesfilme' filme.id %}">
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                        </a>
                    </div>
                    {% endif %}
                    {% endfor %}
                    <a href="#section2" class="arrow__btn text-6xl">›</a>
                </section>
                {% if lista_filmes_recentes|length > 4 %}
                <section id="section2" class="flex flex-nowrap items-center justify-center">
                    <a href="#section1" class="arrow__btn text-6xl">‹</a>
                    {% for filme in lista_filmes_recentes %}
                    {% if forloop.counter > 4 %}
                    <div class="item h-64 w-1/4 m-4">
                        <a href="{% url 'filme:detalhesfilme' filme.id %}">
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                        </a>
                    </div>
                    {% endif %}
                    {% endfor %}
                    <a href="#section1" class="arrow__btn text-6xl">›</a>
                </section>
                {% endif %}
            </div>
        </div>
    </section>
    <section>
        {{ request.user.filmes_vistos.all }}
    </section>

    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative">
            <div class="wrapper grid overflow-visible scroll-smooth">
                <h2 class="text-gray-200 text-2xl font-medium">
                    Novo
                </h2>
                <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
                    <a href="#section2" class="arrow__btn text-6xl page">‹</a>
                    {% for filme in request.user.filmes_vistos.all %}
                    {% if forloop.counter < 5 %}
                    <div class="item h-64 w-1/4 m-4">
                        <a href="{% url 'filme:detalhesfilme' filme.id %}">
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                        </a>
                    </div>
                    {% endif %}
                    {% endfor %}
                    <a href="#section2" class="arrow__btn text-6xl">›</a>
                </section>
                {% if lista_filmes_recentes|length > 4 %}
                <section id="section2" class="flex flex-nowrap items-center justify-center">
                    <a href="#section1" class="arrow__btn text-6xl">‹</a>
                    {% for filme in lista_filmes_recentes %}
                    {% if forloop.counter > 4 %}
                    <div class="item h-64 w-1/4 m-4">
                        <a href="{% url 'filme:detalhesfilme' filme.id %}">
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                        </a>
                    </div>
                    {% endif %}
                    {% endfor %}
                    <a href="#section1" class="arrow__btn text-6xl">›</a>
                </section>
                {% endif %}
            </div>
        </div>
    </section>



</main>








<div class="py-12">
    <hr>
    <u>
    <h1>Essa é nossa homefilmes</h1>
    </u>
    {% for filme in object_list %}
    <hr>
    <a href="{% url 'filme:detalhesfilme' filme.id %}"><p>{{ filme }}</p></a>
    <hr>
    <!-- Div com estilo de fundo vermelho para destacar as informações do filme -->
<div>
        <p><strong>{{ filme.descricao }}</strong></p>
        <img src="{{ filme.thumb.url }}" width="300" height="200">
    </div>

    {% endfor %}
</div>

<div class="py-10">
    <h1>Novo</h1>
    {{ lista_filmes_recentes }}
</div>

<div class="py-10">
    <h1>Em Alta</h1>
    {{ lista_filmes_emalta }}
</div>
{% endblock %}

filme/templates/homepage.html
{% extends 'base.html' %}
{% load static %}


{% block titulo %}
LzkFLIX
{% endblock %}

{% block head %}
<style>
    #id_email{
    width: 100%;
    color: #000000;
    padding: 5px 5px;
    }
</style>

{% endblock %}



{% block content %}

    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/bgnetflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">

            <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
                Filmes e séries da LzkFlix, tudo em um só lugar.
            </h1>
            <h3 class="text-xl md:text-xl py-5">
                Assista onde quiser. Cancele quando quiser.
            </h3>
            <h4 class="text-sm md:text-lg pb-3">
                Quer começar? Coloque seu e-mail abaixo para acessar.
            </h4>

            <div class="w-full flex justify-center">
                <div class="flex justify-center items-center w-11/12 md:w-10/12">
                    <form method="post" class="w-6/12 justify-center">
                        <div class="flex flex-grow items-stretch">
                            {% csrf_token %}
                        <button class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                            {{ form }}
                            <span>
                                Acessar
                            </span>
                            <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                        </button>
                        </div>
                    </form>
                    </a>
                </div>
            </div>

        </div>
    </header>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Enjoy on your TV.
            </h2>
            <h5 class="md:text-xl text-lg">
                Watch on Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players, and more.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/bgnetflix.jpg' %}" class="w-8/12" alt="">
        </div>
    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class='md:w-1/2 flex justify-center items-center '>
            <img src="{% static 'images/mobileflix.jpg' %}" class="w-8/12" alt="">
        </div>

        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Download your shows to watch offline.
            </h2>
            <h5 class="md:text-xl text-lg">
                Save your favorites easily and always have something to watch.
            </h5>
        </div>

    </section>

    <section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
        <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
            <h2 class="md:text-5xl text-4xl font-semibold mb-4">
                Create profiles for kids.
            </h2>
            <h5 class="md:text-xl text-lg">
                Send kids on adventures with their favorite characters in a space made just for them—free with your membership.
            </h5>
        </div>
        <div class='md:w-1/2 flex justify-center items-center'>
            <img src="{% static 'images/netflix_kid.png' %}" class="w-8/12" alt="">
        </div>
    </section>
    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2021</li>
            <li> Feito com Python (Django)</li>
            <li>Hashtag</li>
        </ul>
    </footer>


{% endblock %}

filme/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Fazer Login
{% endblock %}

{% block content %}
    <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/bgnetflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <form method="post">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Faça Login para continuar</legend>
                    {{ form|crispy }}
                </fieldset>
                <button class="bg-red-600 py-1 my-2 px-3 w-full text-white md:text-lg rounded-md" type="submit">Fazer Login</button>
            </form>
            <small>
                Não tem uma conta ainda? <p><a href="{% url 'filme:criarconta' %}">Clique aqui para criar uma conta</a></p>
            </small>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2024</li>
            <li> Feito com Python (Django) LZKSTRAIN</li>
            <li>PROJETO REPLICA</li>
        </ul>
    </footer>
{% endblock %}

filme/templates/logout.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
Logout
{% endblock %}

{% block content %}
   <header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/bgnetflix.jpg' %}');">
        <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
            <h2 class="text-2xl">Você saiu da sua conta</h2>
            <div class="flex flex-nowrap justify-center space-x-5 p-5">
            <a href="{% url 'filme:login' %}"><button class="bg-red-600  py-1 px-3 text-white md:text-lg rounded-md">Fazer Login</button></a>
            <a href="{% url 'filme:criarconta' %}"><button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md">Criar uma Conta</button></a>
            </div>
        </div>
    </header>

    <footer class=" px-5 py-10 ">
        <ul class="flex justify-between items-center">

            <li>&copy; 2021</li>
            <li> Feito com Python (Django)</li>
            <li>lzkstrain</li>
        </ul>
    </footer>
{% endblock %}

filme/templates/navbar.html
{% load static %}


<nav class="w-full flex justify-between items-center py-1 px-4 fixed z-50">
    <div class="w-6/10">
        <a href="/">
            <img class="w-5/12" src="{% static 'images/lzkflixlogo.png' %}">
        </a>

    </div>

    <div class="w-6/12  flex flex-nowrap justify-end">
        {% if user.is_authenticated %}
        <div class="mr-2">
            <form method="post" action="{% url 'filme:pesquisafilme' %}">
                <input type="text" class="py-1 px-2 rounded-md text-black" name="query" value="{{ request.post.query }}" placeholder="Pesquisar...">
                <input type="submit" value="">
            </form>

        </div>
        {% endif %}
        <div class="mr-2">
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'filme:logout' %}">
                {% csrf_token %}
                 <button class="bg-red-600 text-white py-1 px-3 rounded-md" type="submit">Sair</button>
            </form>

            {% else %}
            <a href="{% url 'filme:login' %}">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                    Login
                </button>
            </a>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
        <div class="mr-2">
            <a href="{% url 'filme:editarperfil' request.user.id %}">
                <button class="bg-red-600 text-white py-1 px-3 rounded-md">
                    Editar Perfil
                </button>
            </a>

        </div>

    </div>
    {% endif %}

</nav>

filme/templates/pesquisa.html
{% extends 'base.html' %}

{% block titulo %}
Pesquisa de Filmes
{% endblock %}

{% block content %}
    <main class='bg-primary_black min-h-screen w-full'>
        <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
            <div class="p-8 w-10/12 relative" >
                <h2 class="text-gray-200 text-2xl font-medium">
                    Resultados da Busca
                </h2>
                <div class="flex flex-wrap items-center min-w-full movie_lis">
                  {% for filme in object_list %}
                    <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                        <a href="{% url 'filme:detalhesfilme' filme.id %}">
                          <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt="">
                        </a>
                    </div>
                  {% endfor %}
                </div>


            </div>
        </section>
    </main>
{% endblock %}